#!/bin/bash
PRODUCTION=false

while getopts 'p' opt; do
    case $opt in
        p) PRODUCTION=true ;;
        *) echo 'Error in command line parsing' >&2
               exit 1
    esac
done

if [ ! -d "venv" ]; then
    python3 -m venv venv
    if [ "$PRODUCTION" = true ]; then
        source venv/bin/activate && pip3 install --upgrade pip && pip3 install -r requirements.prod.txt
    else
        source venv/bin/activate && pip3 install --upgrade pip && pip3 install -r requirements.txt
    fi
fi

source venv/bin/activate && exec bash -i
